TESSEorg/ttg

- examples/wavefront/wavefront-df.cc
- examples/wavefront/wavefront-wf.cc
- examples/wavefront/wavefront-wf2.cc
We shouldn't require 2GB per matrix in the wavefront, let's be reasonable here.
> Be more sensible in the wavefront problem size

- examples/potrf/potrf_pdc.cc
- Use provided profiling filename
- Reserve the right amount of space on TRSM
> Minor fixes to the Cholesky benchmark

- examples/potrf/potrf_pdc.cc
- ttg/ttg/base/keymap.h
- ttg/ttg/madness/ttg.h
- ttg/ttg/parsec/ttg.h
- ttg/ttg/world.h
Allows applications to specify a priority map mapping keys to priorities.
The priorities are a hint to the scheduler and may not be supported by
all backends (currently only the PaRSEC backend supports them).
> Add priority mapping to Ops

- bin/docker-build.sh
- bin/docker-travis-build.sh
The docker-build.sh script failed for me on Ubuntu 20.04 with:
`$ bin/docker-build.sh amd64
bin/docker-build.sh: 78: function: not found`
This is due to the use of non-POSIX-standard bash syntax for function definition, which this patch fixes.
> fix non-POSIX-standard function def in shell scripts

- ttg/ttg/parsec/ttg.h
Make the fence implementation in the PaRSEC backend synchronizing by using a barrier. 
Supersedes #119
Closes #119
Fixes #118
> PaRSEC: Add barrier to fence to make it synchronizing

- cmake/modules/FindOrFetchBTAS.cmake
defined manually via macros BLAS_FORTRAN_{LOWER_UPPER_ADD_} and LAPACK_FORTRAN_{LOWER_UPPER_ADD_} if standard Find{BLAS,LAPACK} discovery kits are used
> recent LINALG++ kits expect mangling 

- ttg/ttg/parsec/ttg.h
- Template the task structure on the key type and the potential number of streaming terminals
- Use the local thread's execution stream, if available. Previously, all threads would hammer the same execution stream.
- Avoid locking hash tables where possible to reduce some congestion
- In a broadcast, submit tasks to `__parsec_schedule` at once
> Improvements to the PaRSEC backend

- examples/spmm/spmm.cc
`std::vector::operator[]` does not perform bounds checks so occasionally went oob without noticing, unless we ended up in some strange segfaults.
@evaleev  I actually don't know if this is the proper fix. It might as well just fix the symptoms, not the cause (an actual error in the index calculations...)
> SPMM: stay within index matrix bounds

- examples/spmm/spmm.cc
> matrix metadata traversal uses std::vector::at

- ttg/ttg/parsec/ttg.h
Make sure the task is release if the split-metadata release contains no data to transfer.
Plus minor change when iterating over iovecs provided for the type.
> Fix handling of empty iovecs in PaRSEC backend

- examples/madness/mrattg_streaming.cc
- examples/mrafunctionnode.h
Also add a split metadata descriptor for `FunctionReconstructedNode`
> MRA: add constness to OP inputs and use broadcasts and move

- ttg/ttg/base/world.h
- ttg/ttg/madness/ttg.h
- ttg/ttg/parsec/ttg.h
Also avoid MPI calls in the PaRSEC backend (I was sure I had fixed that somewhere...)
> Devirtualize WorldImpl::size and rank

- ttg/ttg/base/tt.h
- ttg/ttg/util/trace.h
Also, tracing() is just an alias for get_trace()
> Make sure get_trace() always returns a value

- ttg/ttg/base/terminal.h
- ttg/ttg/terminal.h
No need to loop over the successors twice.
> Simplify loops in ttg::Out::send

- ttg/ttg/util/env.cpp
> Add missing stdexcept include to env.cpp

- ttg/ttg/util/hash.h
Simply use the integral value, not need to shuffle around bytes.
> ttg::hash overload for integral values

- ttg/ttg/base/tt.h
It never fails to amaze how different std headers are across platforms...
> Add missing optional header

- ttg/ttg/parsec/ttg.h
Another one from instruction counting La-La-Land:
`PARSEC_LIST_ITEM_SINGLETON` can be inlined while `PARSEC_OBJ_CONSTRUCT` is a sequence of function pointers.
The `parsec_ttg_task_base_t` comes out of a mempool, which constructs the object on first allocation.
> PaRSEC: no need to reconstruct task objects, just make them singletons

- ttg/ttg/parsec/ttg.h
Avoids constly construction of a parsec_list_t
> PaRSEC: replace use of list with ring of tasks

- ttg/ttg/parsec/ttg.h
Copies are appended to the array of copies during a send and removed again at the end of the send call. No need to walk over all other copies.
> PaRSEC: Reverse iteration order in remove_data_copy

- ttg/ttg/make_tt.h
We can store the provided function object (e.g., lambda) directly in the wrapping object, removing the indirection of going through `std::function` when invoking a task.
> Remove std::function indirection in ttg::wrap

- ttg/ttg/base/tt.h
- ttg/ttg/make_tt.h
Some backends (MADNESS) allow to recursively call the function during… the call to send, this the TLS for the outputs need to be stored and restored before/after the function call, or we may work with the wrong outputs
> HOTFIX: make_tt without explicit out parameter does not manage well inline/recursive calling of function

- .github/workflows/cmake.yml
- tests/unit/unit_main.cpp
See https://github.com/nektos/act
Not sure we want to merge it. I'm still seeing the following errors for the unittests:
```
| 25: terminate called after throwing an instance of 'std::runtime_error'
| 25:   what():  locale::facet::_S_create_c_locale name not valid
```
That only occurs on the core-unittests though, all other tests succeed on my machine.
> Adapt the github workflow to run on nektos/act

- .github/workflows/cmake.yml
`OMPI_MCA_btl_vader_single_copy_mechanism` is meant to suppress an error message from an incompatibility between btl/vader and docker, see https://github.com/open-mpi/ompi/issues/4948.
`PARSEC_MCA_runtime_bind_threads` is meant to disable thread binding in PaRSEC, potentially speeding up test runs.
> Github: set OMPI and PaRSEC related env variables and remove setlocale

- ttg/ttg/parsec/ttg.h
This feature is useful if there is sufficient concurrency in the application, with multiple consumers and one subsequent producer on a data. By seting defer_writer(), the application can signal that it is ok to defer the next writer on the data until all readers completed, avoiding the data to be copied. This may lead to a deadlock though, if the execution of the readers
depends on the writer. This feature thus has to be used cautiously.
To enable/disable, call `tt->set_defer_writer(true/false)`.
> Allow TTs to defer a writer if there are readers

- ttg/ttg/traverse.h
Not traversing all TTs leads to nasty deadlocks, e.g., the graph will execute but communication will hang because not all tasks were made executable.
There are valid cases where not all inputs are connected and the user explicitly sets these inputs, e.g., using `invoke`. We should support that and not silently deadlock and make everyone's life miserable.
> Traverse all TTs even if an issue is found

- ttg/ttg/madness/ttg.h
- ttg/ttg/parsec/ttg.h
Otherwise the user controls the key type sent in messages to remote owners of tasks.
> Cast keys passed to invoke() to known key types

- ttg/ttg/func.h
- ttg/ttg/madness/fwd.h
- ttg/ttg/madness/ttg.h
- ttg/ttg/parsec/fwd.h
- ttg/ttg/parsec/ttg.h
PaRSEC needs to make sure that no AMs are delivered before the callbacks are registered, which happens in make_graph_executable. So we add a hook that becomes a barrier for PaRSEC and is empty for madness.
@Ashawini27 this should fix your hangs. Please give it a try and let me know if not :)
> Synchronize on make_graph_executable

- examples/spmm/spmm.cc
- ttg/ttg/terminal.h
Use input_refs_tuple_type instead of input_values_tuple_type. Otherwise inputs will be copied into the tuple, needlessly.
@Ashawini27 You probably want this patch for your performance measurements. Without it, tiles are copied excessively, limiting memory bandwidth and causing contention in the memory manager. 
I'm not even sure why this is exposed, we should clean up the public interface of the TT...
> SPMM: take input by reference, not by value

- cmake/modules/FindTBB.cmake
- ttg/ttg/base/tt.h
- ttg/ttg/madness/ttg.h
- ttg/ttg/parsec/ttg.h
- ttg/ttg/tt.h
... introduce by making a virtual `TTBase::get_world()` stub
> TTG needs get_world() too

- tests/unit/serialization.cc
- ttg/ttg/parsec/ttg.h
- ttg/ttg/serialization/backends/boost/archive.h
- ttg/ttg/serialization/data_descriptor.h
- ttg/ttg/serialization/stream.h
"optimized" archive provided by TTG for Boost serialization into in-memory buffers uses Boost infrastructure (`boost::archive::binary_{i,o}archive_impl`) that makes virtual function calls that cannot be inlined at compile time (see #274 ). This addresses the issue.
> Boost serialization: avoid virtual function calls

- cmake/modules/FindOrFetchBoost.cmake
- examples/CMakeLists.txt
- examples/spmm/spmm.cc
> SPMM: add Boost::graph as dependency

- ttg/ttg/tt.h
TTs may return ttg::coroutine_handle (make_tt) or ttg::device::Task (custom TTs)
> Add static assert for task return and check for derived of ttg::coroutine_handle

- examples/CMakeLists.txt
- examples/devblas_helper.h
- examples/potrf/potrf.h
- examples/spmm/spmm_cuda.cc
We can detect both HIP and CUDA on some machines but may only build one at the time.
> Change guards for CUDA/HIP/L0 to TTG_ENABLE_*

- cmake/modules/FindOrFetchBoost.cmake
this is only for building Boost from source
> [cmake] Boost::graph needs its dependencies to be spelled out fully

- examples/spmm/spmm_cuda.cc
Add a simple device mapping for the SPMM benchmark. This mapping mashes together `i` and `j` such that all `k` for `[i, j]` run on the same device. Maybe there are better approaches?
Here is the performance on Seawulf:
1 device:
```
TTG-PARSEC PxQxR=   1 1 1 1 average_NB= 1.00033e+06 M= 1200 N= 16384 K= 16384 t= 1024 T=1024 Tiling= RandomIrregularTiling A_density= 1 B_density= 1 gflops= 644.245 seconds= 0.163009 gflops/s= 3952.21
TTG-PARSEC PxQxR=   1 1 1 1 average_NB= 1.00033e+06 M= 1200 N= 16384 K= 16384 t= 1024 T=1024 Tiling= RandomIrregularTiling A_density= 1 B_density= 1 gflops= 644.245 seconds= 0.115536 gflops/s= 5576.14
TTG-PARSEC PxQxR=   1 1 1 1 average_NB= 1.00033e+06 M= 1200 N= 16384 K= 16384 t= 1024 T=1024 Tiling= RandomIrregularTiling A_density= 1 B_density= 1 gflops= 644.245 …
```
> Add devicemap to spmm benchmark

- .github/workflows/cmake.yml
See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Bumping the action/checkout version should fix these warnings:
```
macos-latest: clang++ Release
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/cache@v1.1.0. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```
> Bump `actions/{checkout, cache}` version to v4

- ttg/ttg/buffer.h
- ttg/ttg/device/device.h
- ttg/ttg/device/task.h
- ttg/ttg/parsec/buffer.h
- ttg/ttg/parsec/devicefunc.h
- ttg/ttg/parsec/fwd.h
- ttg/ttg/parsec/task.h
- ttg/ttg/parsec/ttg.h
- ttg/ttg/parsec/ttg_data_copy.h
Set of changes made while implementing the first MRA kernels with device support. More to come but I wanted to get these out.
Summary:
- Allow specifying the scope (allocate/syncin) on buffers. This is useful for data that is first produced on the device to avoid the initial transfer.
- Allowing `const T` on `ttg::Buffer` to specify that the content of the buffer is immutable.
- Device-side bindings for `broadcastk`
- Deferring errors as long as possible if a type is not copyable. We will try to defer the mutating task until all consumers of the object have completed. Only if we find a second mutating task on the same object we have to throw our hands up.
- Introduce `ttg::device::Stream` representing a device stream object.
- Couple of minor fixes
I tried to break down the changes into …
> Upstream improvements needed for MRA on devices

- ttg/ttg/parsec/ttg.h
Check whether thinks that all devices can access the memory of their peers. If so, we do not need to push modified data back to the host as PaRSEC will use D2D transfers instead of the host copy. We currently stick to the owner-computes model so data will always be modified on the same device and may only be read on a different device.
> PaRSEC: check for universal peer access

- .github/workflows/cmake.yml
- CMakeLists.txt
Checks currently fail because Umpire/librett fails to find CUDA.
> Add workflow for building TTG with CUDA support

- CMakeLists.txt
- examples/CMakeLists.txt
- examples/floyd-warshall/floyd_warshall_df.cc
No code is actually using OpenMP. Some examples still have OpenMP commented out. I'll leave it there for historical reasons.
> Remove OpenMP dependency

- ttg/ttg/parsec/ttg.h
Yes, there was a bug. Yes, PaRSEC says devices cannot access themselves. This code should be trivial. Alas...
> Fix check for peer access.

- tests/unit/device_coro.cc
- ttg/CMakeLists.txt
- ttg/ttg.h
- ttg/ttg/base/tt.h
- ttg/ttg/buffer.h
- ttg/ttg/device/device.h
- ttg/ttg/device/task.h
- ttg/ttg/devicescratch.h
- ttg/ttg/madness/buffer.h
- ttg/ttg/madness/devicefunc.h
- ttg/ttg/madness/fwd.h
- ttg/ttg/madness/ttg.h
- ttg/ttg/make_tt.h
- ttg/ttg/parsec/buffer.h
- ttg/ttg/parsec/devicefunc.h
- ttg/ttg/parsec/fwd.h
- ttg/ttg/parsec/parsec-ext.h
- ttg/ttg/parsec/ttg.h
- ttg/ttg/ptr.h
- ttg/ttg/terminal.h
- ttg/ttg/util/meta.h
Next set of changes needed for MRA. This change set allows buffers to be empty and const and enables tasks to define a flexible set of device inputs using `ttg::device::Input`, which is a vector of buffers internals provided by the backend implementation.
> Flexible device inputs

- ttg/ttg/parsec/ttg.h
Needed to fix build with CUDA.
> Hotfix: reference global make_executable

- examples/spmm/spmm.cc
- ttg/ttg/madness/fwd.h
- ttg/ttg/madness/ttg.h
- ttg/ttg/make_tt.h
- ttg/ttg/parsec/fwd.h
- ttg/ttg/parsec/task.h
- ttg/ttg/parsec/ttg.h
Defaults to Host execution so existing code is not affected. Properly set by make_tt.
We cannot query TT::derivedT for flags because at the time TT is instantiated because derivedT is incomplete at that point. For now pass the Space as template parameter. We need to find a different way if we want to have multiple implementations of a task.
> Pass the Execution Space as TT template parameter

- ttg/ttg/parsec/ttg.h
If the user requested PaRSEC to enable dag profiling we should just play ball and enable our part of it. The user can still enable dag profiling programmatically.
> PaRSEC: enable dag profiling if enabled through PaRSEC mca

- ttg/ttg/parsec/ttg.h
We have to make sure that the taskpool is enabled before we allow anyone to send us messages, otherwise PaRSEC's termination detector will bark at us.
> PaRSEC: Defer handling of messages if termination detector is not ready yet
